spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  data:
    web:
      pageable:
#       웹 요청 들어왔을 때 페이징 처리된 값을 0이 아닌 1부터 시작
        one-indexed-parameters: true
        default-page-size: 5

  datasource:
    url: jdbc:h2:mem:jkboard
    username: sa
    password:
    driver-class-name: org.h2.Driver